/**
 * Input validation + sanitization helpers (no external dependencies).
 */

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

export function isEmail(v: unknown): v is string {
  return typeof v === "string" && v.length <= 254 && EMAIL_RE.test(v);
}

/** Trims and strips control characters; hard-caps length. */
export function cleanText(v: unknown, maxLen: number): string {
  if (typeof v !== "string") return "";
  return v.replace(/[\u0000-\u001f\u007f]/g, " ").trim().slice(0, maxLen);
}

/** Caption stored verbatim but length-capped; React escapes on render. */
export function cleanCaption(v: unknown): string {
  return cleanText(v, 80);
}

export function cleanMultiline(v: unknown, maxLen: number): string {
  if (typeof v !== "string") return "";
  return v
    .replace(/\r\n/g, "\n")
    .replace(/[\u0000-\u0009\u000b-\u001f\u007f]/g, "")
    .trim()
    .slice(0, maxLen);
}

/** Slugs/ids: lowercase alphanumerics and dashes only. */
export function cleanSlug(v: unknown, maxLen = 80): string {
  const s = cleanText(v, maxLen).toLowerCase();
  return /^[a-z0-9][a-z0-9-]*$/.test(s) ? s : "";
}

/** Short opaque identifiers generated by the app (base64url). */
export function cleanId(v: unknown, maxLen = 64): string {
  const s = cleanText(v, maxLen);
  return /^[A-Za-z0-9_-]+$/.test(s) ? s : "";
}

export function isStrongEnough(problems: string[]): boolean {
  return problems.length === 0;
}

/* ------------------------------------------------------------------ */
/* Pagination                                                          */
/* ------------------------------------------------------------------ */

export interface PageParams {
  limit: number;
  cursor: string | null;
}

/** Clamped page size — callers can never request an unbounded page. */
export function parsePageParams(
  url: string,
  { defaultLimit = 12, maxLimit = 50 }: { defaultLimit?: number; maxLimit?: number } = {}
): PageParams {
  const params = new URL(url).searchParams;
  const raw = Number(params.get("limit"));
  const limit = Number.isFinite(raw)
    ? Math.min(maxLimit, Math.max(1, Math.floor(raw)))
    : defaultLimit;
  return { limit, cursor: params.get("cursor") };
}

/** Cursor = base64url(created_at|id) — stable ordering for keyset paging. */
export function encodeCursor(createdAt: string, id: string): string {
  return Buffer.from(`${createdAt}|${id}`).toString("base64url");
}

export function decodeCursor(cursor: string | null): { createdAt: string; id: string } | null {
  if (!cursor || cursor.length > 200) return null;
  try {
    const decoded = Buffer.from(cursor, "base64url").toString("utf8");
    const sep = decoded.lastIndexOf("|");
    if (sep < 1) return null;
    const createdAt = decoded.slice(0, sep);
    const id = decoded.slice(sep + 1);
    if (Number.isNaN(Date.parse(createdAt))) return null;
    if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) return null;
    return { createdAt, id };
  } catch {
    return null;
  }
}

/* ------------------------------------------------------------------ */
/* Images                                                              */
/* ------------------------------------------------------------------ */

/** Base64 data-URL → buffer, with declared size check. */
export function parseDataUrl(
  dataUrl: string,
  maxBytes: number
): { buf: Buffer; mime: string } | null {
  if (typeof dataUrl !== "string") return null;
  if (dataUrl.length > Math.ceil(maxBytes * 1.4) + 128) return null; // cheap pre-check
  const m = /^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl);
  if (!m) return null;
  const [, mime, b64] = m;
  const buf = Buffer.from(b64, "base64");
  if (buf.length === 0 || buf.length > maxBytes) return null;
  return { buf, mime };
}

/** Magic-byte sniffing so a renamed .exe can't pass as a PNG. */
export function imageMime(buf: Buffer): "png" | "jpeg" | "webp" | null {
  if (buf.length < 12) return null;
  if (buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47)
    return "png";
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "jpeg";
  if (
    buf.subarray(0, 4).toString("ascii") === "RIFF" &&
    buf.subarray(8, 12).toString("ascii") === "WEBP"
  )
    return "webp";
  return null;
}

export const extensionFor = (mime: "png" | "jpeg" | "webp"): "png" | "jpg" | "webp" =>
  mime === "jpeg" ? "jpg" : mime;

export const contentTypeFor = (mime: "png" | "jpeg" | "webp"): string =>
  `image/${mime}`;
